# Permalinks
permalink: pretty

# Setup
title: "Transportation Data and Performance Hub | City of Austin Transportation Department"
tagline: "Open Data Projects at the Austin Transportation Department"
description: ""
url: "https://data.mobility.austin.gov"

author:
  name: ""
  url: ""

# Custom vars
version: 0.0.0

github:
  repo: https://github.com/cityofaustin/atd-data-and-performance

exclude: ["node_modules"]

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
